export const AVAILABLE_SCOPES = [
  "read:accounts",
  "write:accounts",
  "read:journal-entries",
  "write:journal-entries",
  "read:customers",
  "write:customers",
  "read:vendors",
  "write:vendors",
  "read:invoices",
  "write:invoices",
  "read:bills",
  "write:bills",
  "read:payments",
  "write:payments",
  "read:expenses",
  "write:expenses",
  "read:reports",
  "read:banking",
  "write:banking",
] as const;
